import 'dart:io';
import 'dart:typed_data';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:share_plus/share_plus.dart';

/// Mobile-specific implementation for PDF file operations
/// Uses file system and native share dialog
class PdfFilePlatform {
  /// Save PDF to application documents directory (mobile implementation)
  /// Returns the file path
  static Future<String> savePdfToFile(pw.Document pdf, String fileName) async {
    try {
      final bytes = await pdf.save();
      final directory = await getApplicationDocumentsDirectory();
      final file = File('${directory.path}/$fileName');
      await file.writeAsBytes(bytes);
      return file.path;
    } catch (e) {
      throw Exception('Failed to save PDF: $e');
    }
  }

  /// Share PDF file using native share dialog (mobile implementation)
  static Future<void> sharePdf(
    String filePath,
    Uint8List bytes,
    String fileName,
  ) async {
    try {
      final result = await Share.shareXFiles(
        [XFile(filePath)],
        subject: 'ComplyHealth Medication Report',
        text: 'Medication report generated by ComplyHealth',
      );

      // Result status is available for debugging
      if (result.status == ShareResultStatus.success) {
        // Successfully shared
      }
    } catch (e) {
      throw Exception('Failed to share PDF: $e');
    }
  }
}
