// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLBh7moBJAninHLCIS3oAbP7OV2SdyoFc',
    appId: '1:818057086992:web:e268fbf538829a23342295',
    messagingSenderId: '818057086992',
    projectId: 'smart-patient-65009',
    authDomain: 'smart-patient-65009.firebaseapp.com',
    storageBucket: 'smart-patient-65009.firebasestorage.app',
    measurementId: 'G-N7P9TTJ7KG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5l9J18PYeM3yBBaM_wOv_DgTaRXq0osA',
    appId: '1:818057086992:android:680c4bb85fb9132e342295',
    messagingSenderId: '818057086992',
    projectId: 'smart-patient-65009',
    storageBucket: 'smart-patient-65009.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgb0PrH9x1FNanBNWRUf-q-Oqk7SLi_-Q',
    appId: '1:818057086992:ios:ec89edfedd060a30342295',
    messagingSenderId: '818057086992',
    projectId: 'smart-patient-65009',
    storageBucket: 'smart-patient-65009.firebasestorage.app',
    iosBundleId: 'com.example.smartpatient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgb0PrH9x1FNanBNWRUf-q-Oqk7SLi_-Q',
    appId: '1:818057086992:ios:ec89edfedd060a30342295',
    messagingSenderId: '818057086992',
    projectId: 'smart-patient-65009',
    storageBucket: 'smart-patient-65009.firebasestorage.app',
    iosBundleId: 'com.example.smartpatient',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLBh7moBJAninHLCIS3oAbP7OV2SdyoFc',
    appId: '1:818057086992:web:5bf21e8ccddfeb78342295',
    messagingSenderId: '818057086992',
    projectId: 'smart-patient-65009',
    authDomain: 'smart-patient-65009.firebaseapp.com',
    storageBucket: 'smart-patient-65009.firebasestorage.app',
    measurementId: 'G-SN710CEV0D',
  );
}
