// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:complyhealth/core/models/disease.dart';
import 'package:complyhealth/core/models/education_content.dart';
import 'package:complyhealth/core/models/feedback.dart';
import 'package:complyhealth/core/models/medication.dart';
import 'package:complyhealth/core/models/medication_log.dart';
import 'package:complyhealth/core/models/notebook_entry.dart';
import 'package:complyhealth/core/models/profile.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ArticleAdapter());
    registerAdapter(DiseaseAdapter());
    registerAdapter(DoseStatusAdapter());
    registerAdapter(EducationContentAdapter());
    registerAdapter(FeedbackAdapter());
    registerAdapter(MedicationAdapterGenerated());
    registerAdapter(MedicationLogAdapter());
    registerAdapter(NotebookEntryAdapter());
    registerAdapter(ProfileAdapter());
    registerAdapter(VideoAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ArticleAdapter());
    registerAdapter(DiseaseAdapter());
    registerAdapter(DoseStatusAdapter());
    registerAdapter(EducationContentAdapter());
    registerAdapter(FeedbackAdapter());
    registerAdapter(MedicationAdapterGenerated());
    registerAdapter(MedicationLogAdapter());
    registerAdapter(NotebookEntryAdapter());
    registerAdapter(ProfileAdapter());
    registerAdapter(VideoAdapter());
  }
}
